# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spider',
            old_name='cont',
            new_name='text',
        ),
    ]
